#gs = global static
import time

#we don't need floats to keep timestamps
def getTime():
    return int(time.time())

def safeConvertToInt(val):
    newVal = 0
    try:
        newVal = int(val)
    except:
        return None

    return newVal

def safeConvertToFloat(val):
    newVal = 0.0
    try:
        newVal = float(val)
    except:
        return None

    return newVal


def formatFloatStr(num, places):
    fmt = "%." + str(places) + "f"
    #print fmt
    return fmt % num

gsPLAYERDBLOC = "playersdb"
gsPLAYEROBJFILEEXT = "plr"

gsFRANCHISEDBLOC = "franchisesdb"
gsFRANCHISEOBJFILEEXT = "frn"

gsGLOBALSDBLOC = "globalsdb"
gsGLOBALSOBJFILEEXT = "gbl"

#the farthest someone with Power = 0 can hit the ball
gsPLAYER_POWER_MAX_RADIUS_INIT = 425

gsLEVEL_CASH_PERPRESTIGE_PERGAME = 100

gsPLAYERENERGY_MAXINITIAL = 10
gsPLAYERRECOVERYTIME_INITIAL = (5*60) #seconds
gsPLAYERCHALLENGE_MAXINITIAL = 5
gsINITIAL_STATPOINT_ALLOC = 10
gsINITIAL_MONEY_ALLOC = 1000
gsPLAYER_INIT_PRESTIGE = 1

gsBATTING_LINEUP_LENGTH = 9
gsPLAYERFREEAGENT = -1

gsMAXGAMEINNINGS = 9
gsOUTSPERINNING = 3
gsBASEEMPTY = -1
gsOUTSPERGAME = gsOUTSPERINNING * gsMAXGAMEINNINGS


############
#
# These Constants
# are also defined
# ServerApi.py and need to remain consistent
############

PLAYERABILITIES = 'PLYRABILS'
PLAYERABILITIES_BATTING = 'PLYRABIL_BATTNG'
PLAYERABILITIES_PITCHING = 'PLYRABIL_PITCHNG'
PLAYERABILITIES_FIELDING = 'PLYRABIL_FLDNG'
PLAYERABILITIES_CHARACTER = 'PLYRABIL_CHAR'

#Common Abilities:
PLAYERABILITY_MAXENERGYPOINTS =    'PLYRABIL_MAXENG'
PLAYERABILITY_MAXCHALLENGEPOINTS = 'PLYRABIL_MAXCHAL'
PLAYERABILITY_DEFENSE =            'PLYRABIL_DEFENSE'
PLAYERABILITY_PRESTIGE =           'PLYRABIL_PRSTIGE' 
PLAYERABILITY_LEADERSHIP =         'PLYRABIL_LDRSHIP'

#Batter Abilities:
PLAYERABILITY_BATTER_POWER =       'PLYRABIL_BATPWR'
PLAYERABILITY_BATTER_PATIENCE =    'PLYRABIL_BATPTNC'

#Pitcher Abilities:
PLAYERABILITY_PITCHER_CONTROL =    'PLYRABIL_PITCTRL'
PLAYERABILITY_PITCHER_STAMINA =    'PLYRABIL_PITSTAM'

#Pitch Types
gsCURVEBALL = 'CRV'
gsFASTBALL = 'FST'
gsSLIDER = 'SLD'
gsCHANGEUP = 'CHNG'
gsKNUCKLEBALL = 'KNCK'
gsSINKER = 'SINK'
gsSPITBALL = 'SPIT'
gsFORKBALL = 'FORK'

gsPITCHTYPES = [gsFASTBALL, 
                gsCURVEBALL, 
                gsSLIDER,
                gsCHANGEUP, 
                gsKNUCKLEBALL, 
                gsSINKER, 
                gsSPITBALL,
                gsFORKBALL]

PLAYERSKILLS_BATTERSKILLS = 'PLYRSKILLS_BAT'
PLAYERSKILLS_PITCHERSKILLS = 'PLYRSKILLS_PIT'

PLAYERSKILLTRAINING_GUID       =  'GUID'
PLAYERSKILLTRAINING_MONEYCOST  =  'MONEYCOST'
PLAYERSKILLTRAINING_ENERGYCOST =  'ENRGYCOST'
PLAYERSKILLTRAINING_TEXTDESC   =  'TEXTDESC'
PLAYERSKILLTRAINING_SKILLTYPE =   'SKILLTYPE'
PLAYERSKILLTRAINING_SKILLSINC =   'SKILLSINC'


PLAYERSKILLTRAINING_PITCHERZONETYPE = 'PITZONE'
PLAYERSKILLTRAINING_PITCHERPITCHTYPE = 'PITPITCH'
PITCHERSKILLS = [PLAYERSKILLTRAINING_PITCHERZONETYPE,
                 PLAYERSKILLTRAINING_PITCHERPITCHTYPE]

PLAYERSKILLTRAINING_BATTERZONETYPE =  'HITZONE'
PLAYERSKILLTRAINING_BATTERPITCHTYPE = 'HITPITCH'
BATTERSKILLS = [PLAYERSKILLTRAINING_BATTERZONETYPE,
                PLAYERSKILLTRAINING_BATTERPITCHTYPE]

PLAYERSKILLID_PITCHER_PITCH_FASTBALL =    gsFASTBALL #'PIT' + gsFASTBALL
PLAYERSKILLID_PITCHER_PITCH_CURVEBALL =   gsCURVEBALL #'PIT' + gsCURVEBALL
PLAYERSKILLID_PITCHER_PITCH_SLIDER =      gsSLIDER #'PIT' + gsSLIDER
PLAYERSKILLID_PITCHER_PITCH_CHANGEUP =    gsCHANGEUP #'PIT' + gsCHANGEUP
PLAYERSKILLID_PITCHER_PITCH_FORKBALL =    gsFORKBALL#'PIT' + gsFORKBALL
PLAYERSKILLID_PITCHER_PITCH_SINKER =      gsSINKER#'PIT' + gsSINKER
PLAYERSKILLID_PITCHER_PITCH_SPITBALL =    gsSPITBALL#'PIT' + gsSPITBALL
PLAYERSKILLID_PITCHER_PITCH_KNUCKLEBALL = gsKNUCKLEBALL#'PIT' + gsKNUCKLEBALL

PLAYERSKILLID_PITCHER_ZONE_0 = 0#'PIT' + 'ZONE0'
PLAYERSKILLID_PITCHER_ZONE_1 = 1#'PIT' + 'ZONE1'
PLAYERSKILLID_PITCHER_ZONE_2 = 2#'PIT' + 'ZONE2'
PLAYERSKILLID_PITCHER_ZONE_3 = 3#'PIT' + 'ZONE3'
PLAYERSKILLID_PITCHER_ZONE_4 = 4#'PIT' + 'ZONE4'
PLAYERSKILLID_PITCHER_ZONE_5 = 5#'PIT' + 'ZONE5'
PLAYERSKILLID_PITCHER_ZONE_6 = 6#'PIT' + 'ZONE6'
PLAYERSKILLID_PITCHER_ZONE_7 = 7#'PIT' + 'ZONE7'
PLAYERSKILLID_PITCHER_ZONE_8 = 8#'PIT' + 'ZONE8'


PLAYERSKILLID_BATTER_PITCH_FASTBALL =    gsFASTBALL#'HIT' + gsFASTBALL
PLAYERSKILLID_BATTER_PITCH_CURVEBALL =   gsCURVEBALL #'HIT' + gsCURVEBALL
PLAYERSKILLID_BATTER_PITCH_SLIDER =      gsSLIDER #'HIT' + gsSLIDER
PLAYERSKILLID_BATTER_PITCH_CHANGEUP =    gsCHANGEUP #'HIT' + gsCHANGEUP
PLAYERSKILLID_BATTER_PITCH_FORKBALL =    gsFORKBALL #'HIT' + gsFORKBALL
PLAYERSKILLID_BATTER_PITCH_SINKER =      gsSINKER #'HIT' + gsSINKER
PLAYERSKILLID_BATTER_PITCH_SPITBALL =    gsSPITBALL  #'HIT' + gsSPITBALL
PLAYERSKILLID_BATTER_PITCH_KNUCKLEBALL = gsKNUCKLEBALL #'HIT' + gsKNUCKLEBALL


PLAYERSKILLID_BATTER_ZONE_0 = 0#'HIT' + 'ZONE0'
PLAYERSKILLID_BATTER_ZONE_1 = 1#'HIT' + 'ZONE1'
PLAYERSKILLID_BATTER_ZONE_2 = 2#'HIT' + 'ZONE2'
PLAYERSKILLID_BATTER_ZONE_3 = 3#'HIT' + 'ZONE3'
PLAYERSKILLID_BATTER_ZONE_4 = 4#'HIT' + 'ZONE4'
PLAYERSKILLID_BATTER_ZONE_5 = 5#'HIT' + 'ZONE5'
PLAYERSKILLID_BATTER_ZONE_6 = 6#'HIT' + 'ZONE6'
PLAYERSKILLID_BATTER_ZONE_7 = 7#'HIT' + 'ZONE7'
PLAYERSKILLID_BATTER_ZONE_8 = 8#'HIT' + 'ZONE8'

#Position Codes (INTs)
gsPITCHER_POSCODE,gsCATCHER_POSCODE,gsFIRSTBASE_POSCODE, \
    gsSECONDBASE_POSCODE, gsTHIRDBASE_POSCODE, gsSHORTSTOP_POSCODE, \
    gsLEFTFIELDER_POSCODE, gsCENTERFIELDER_POSCODE, gsRIGHTFIELDER_POSCODE, \
    gsDESIGNATEDHITTER_POSCODE = range(1,11)

#Position Codes (STRs) POSCODE -> POSSTR
gsPOSITION_POSSTR = {1:'P',2:'C',3:'1B',
                     4:'2B',5:'3B',6:'SS',
                     7:'LF',8:'CF',9:'RF',10:'DH'}


gsHOMEBASE = 0
gsFIRSTBASE = 1
gsSECONDBASE = 2
gsTHIRDBASE = 3

#x,y from top left as origin going down
#gsSTRIKEZONES = [(0,2),(1,2),(2,2),
#                 (0,1),(1,1),(2,1),
#                 (0,0),(1,0),(2,0)]

gsPITCHZONES = range(0,10)#range() is non-inclusive on end
#TODO: Add Zones for HBP and WILDPITCH
gsSTRIKEZONE = range(9)
gsBALLZONE = 9

gsPITCHCALL_STRIKE = 'STRK'
gsPITCHCALL_BALL = 'BALL'
gsPITCHCALL_FOUL = 'FOUL'
gsPITCHCALL_CONTACT = 'CONT'

gsMAXSTRIKECOUNT = 3
gsMAXBALLCOUNT = 4


gsPITCHCALL_STRIKEOUT = 'SO'
gsPITCHCALL_WALK = 'BB'
gsPITCHCALL_HITBYPITCH = 'HBP'
#gsPITCHCALL_INTENTIONALWALK = 'IBB'

#AtBatResult Codes (Strings) 
#
# FMT for an AT BAT Result is:
#         RESULT_CODE (batterGUID, pitcherGUID, pitchType, pitchZone, pitchSpeed, pitchCount, hitLocation (coordinates off the bat), fielderGUID(or NONE), RunnerAdvance List or NONE)
#
# RUNNERADV format is runnerGUID(base0, baseF) : 
#            where 0 is home first is 1, etc...
#
gsNULL_ATBATRESULT_CODE = ""
gsATBATRESULT_SINGLE = '1B'
gsATBATRESULT_DOUBLE = '2B'
gsATBATRESULT_TRIPLE = '3B'
gsATBATRESULT_HOMERUN = 'HR'
gsATBATRESULT_GROUNDOUT = 'GO'
gsATBATRESULT_AIROUT = 'AO'
gsATBATRESULT_SACOUT = 'SAC'
gsATBATRESULT_DOUBLEPLAY = 'DP'
gsATBATRESULT_TRIPLEPLAY = 'TP'

gsATBATRESULT_STRIKEOUT = gsPITCHCALL_STRIKEOUT
gsATBATRESULT_WALK = gsPITCHCALL_WALK
gsATBATRESULT_HITBYPITCH = gsPITCHCALL_HITBYPITCH
#gsATBATRESULT_INTENTIONALWALK = gsPITCHCALL_INTENWALK

gsCONTACTMADEEVENTS = [gsATBATRESULT_SINGLE,
                       gsATBATRESULT_DOUBLE,
                       gsATBATRESULT_TRIPLE,
                       gsATBATRESULT_HOMERUN,
                       gsATBATRESULT_GROUNDOUT,
                       gsATBATRESULT_AIROUT,
                       gsATBATRESULT_SACOUT,
                       gsATBATRESULT_DOUBLEPLAY,
                       gsATBATRESULT_TRIPLEPLAY,]

#gsBATTINGEVENTS = ['1B','2B','3B','HR','BB','SO','HBP',
#                   'GO','AO','SAC','DP','TP']#,'IBB']
gsHITS = ['1B','2B','3B','HR']
gsNOTATBAT = ['BB','HBP']
#gsDONTADDPITCH = ['SO','BB']
gsSINGLEOUTPLAYS = ['GO','SO','AO','SAC']
gsMULTIOUTPLAYS = ['DP','TP']
gsOUTEVENTS = gsSINGLEOUTPLAYS + gsMULTIOUTPLAYS
gsRUNNERSADVANCEEVENTS = gsHITS + ['BB','HBP','SAC']
gsMAXPITCHCOUNT = 10





class GlobalState:
 
    def __init__(self):
        self.__nextPlayerGUID = 0
        self.__nextFranchiseGUID = 0
        return

    def __str__(self):
        return self.__getstate__()

    def nextPlayerGUID(self):
        self.__nextPlayerGUID += 1
        return self.__nextPlayerGUID - 1
    
    def nextFranchiseGUID(self):
        self.__nextFranchiseGUID += 1
        return self.__nextFranchiseGUID - 1

    def __getstate__(self):
        state = "{'nextPlayerGUID':%d,'nextFranchiseGUID':%d}" % (self.__nextPlayerGUID, self.__nextFranchiseGUID)
        return state 

    def __setstate__(self, dictStr):
        print "TODO: check for eval errors when loading Global State"        
        d = eval(dictStr)
        self.__nextPlayerGUID = d['nextPlayerGUID']
        self.__nextFranchiseGUID = d['nextFranchiseGUID']
        return self

#globalState = GlobalState()
